### ISSUE TITLE
add starting values for the coefficients

### ISSUE THREAD

**Issue by BenoitLondon** [shabbychef/ohenery#7]
Sometimes we add more data and would like to refit the model starting from a previous fit/ coefficients

currently it is harcoded to zeroes in .hmfit

**Comment by shabbychef** [comment]
My comments say things like `2FIX: allow beta0 input` in a few places, so this has been on my todo list.
warm start should be easy in `.hmfit`, but the public facing API is a bit harder. 
If we rely on users to give the coefficients in the proper order, there could be a mismatch. Alternatively we could allow to restart from an existing `hensm` object, which we would have to interpret.
I will have to think about this; what is your proposed interface?

**Comment by shabbychef** [comment]
Here is where I have landed: I will expand `hensm` and `harsm` to accept objects of the same class as `fit0`. I will then peel beta and gamma coefficients from the fit. If any beta are missing, they will be initialized with zeros. If any gamma are missing, they are initialized as 1. This should, I think, cover three use cases:
1. want to refit the same model but with different data
2. want to fit a similar model, but removing some of the predictive variables or adding new predictive variables.
3. want to fit a similar model but tweaking the number of fit gammas.

**Comment by shabbychef** [comment]
The user can specify a different `ngamma` for the third use case. If they do not specify a `ngamma` and include a `fit0`, the previous `ngamma` applies.

**Comment by shabbychef** [comment]
I just pushed these changes to version 0.1.1.901 in the `dev` branch via 14d2d4a254382cbf996684a6aaa1d75416908207 . Only for `hensm` at the moment. PTAL.

**Comment by shabbychef** [comment]
Similarly, `harsm` can now accept a warm start parameter.
Both also allow you to specify the other kind of object and will ignore the gamma parameters,
so you can warm start from one to the other.
Closing this now, as warm start will be in the next release, or you can install from `dev.

**Comment by BenoitLondon** [comment]
rockstar!

**Comment by shabbychef** [comment]
pushed to CRAN as 0.1.2.
